### ISSUE TITLE
python 2.7.9+ and SSL context

### ISSUE THREAD

**Issue by rhavenn** [schubergphilis/Check_Nexenta#5]
URLLib2 breaks if you have SSL without a legitimate cert in Python 2.7.9. To disable SSL verification do the following:

import ssl

then in the get_data section define:
sslcontext = ssl._create_unverified_context()

I put this before the "tries" section. Then change the urllib request to:
response = json.loads(urllib2.urlopen(request, context=sslcontext).read())

I'm guessing maybe add a flag for this?

Thanks for your code.

**Comment by jm66** [comment]
I use the following validation:
```
if sys.version.split(' ')[0] == '2.7.9':
    ssl._create_default_https_context = ssl._create_unverified_context
```
