### ISSUE TITLE
NexentaStor license will expire in 30 days.

### ISSUE THREAD

**Issue by dangul** [schubergphilis/Check_Nexenta#6]
Hi, even if we got a permanent license that is vaild we getting following warning from check_nexenta.py plugin:

nms-licensecheck:NOTICE: Warning! NexentaStor license will expire in 30 days.

The expire date does not change at all. We are using NexentaStor 4.0.3?

Could it be a bug in check_nexenta.py ?

**Comment by dangul** [comment]
Sorry, we are using check_nexenta.py version 1.0.13

**Comment by brennoosterbaan** [comment]
Hi Dangul,

If you check the nexentastor GUI and go to triggers you'll probably see the nms-licensecheck trigger is still stating this warning. If you clear the trigger the warning will go away and check_nexenta will stop reporting it.

what check_nexenta does is list all triggers that Nexenta has configured and report the messages and severity levels.

regards,

Brenn

**Comment by dangul** [comment]
Yes, you mean GUI - > Triggers ? We aware about that but there is no nms-licensecheck in GUI. Could be changed in 4.0 of NexaStor. Is NexaStor 4.0.3 "supported" by check_nexenta ?

**Comment by brennoosterbaan** [comment]
I don't have 4.0 running so have not tested it.
My point is that the check does an API call where it asks the system which runners are available. Next it asks the state of each runner.
There is no way for the check itself to come up with this warning without the API telling it to the check.

If you can not find the runner/trigger to clear you can always use the configuration file. There you can change the severity levels of all warnings/messages. If you change it to IGNORE it will no longer be reported.

regards,

Brenn

**Comment by dangul** [comment]
Ah, ok... I didn´t know about IGNORE. Thanks! I will check Nexenta if they know anything about nms-licencecheck and how to clear it :)

**Comment by madic-creates** [comment]
I had the same problem on 4.0.4. Needed to fix it in the sqlite db...
sqlite3 /var/lib/nza/report.db
sqlite> delete from faults where trigger = "nms-licensecheck";
sqlite> .exit
